### ISSUE TITLE
小兄弟,看过心理医生吗？建议去看看心理医生呢

### ISSUE THREAD

**Issue by iamzhaoritian** [WhaleFell/dxyMedicineSpider#3]

**Comment by WhaleFell** [comment]
Certainly seen a psychiatrist and currently on medication for mental illness.

**Comment by WhaleFell** [comment]
Diagnosis of bipolar disorder.This is a Wikipedia entry:https://en.wikipedia.org/wiki/Bipolar_disorder/wiki/Bipolar_disorder.

Thank you for your care. :)

~But it won't stop me from leaving this world~

**Comment by WhaleFell** [comment]
Please close this issue if there is nothing else to do.
