### ISSUE TITLE
小兄弟，一身的才华，莫要浪费，搞破坏带来的一时快感，没有做正事带来的成就感有趣。

### ISSUE THREAD

**Issue by iamzhaoritian** [WhaleFell/dxyMedicineSpider#4]

**Comment by WhaleFell** [comment]
**Alert**: This is an **NSFW** (**N**ot **S**ee **F**or **W**ork) comment.

![image](https://user-images.githubusercontent.com/63758849/171419152-61011e5e-3665-4945-9a2f-6d78c49b29c0.png)

> It is painful for me to live in this world, so please don't talk me out of it.
